//@GeneratedCode
namespace QTHungryDogs.Logic
{
    ///
    /// Generated by the generator
    ///
    public static partial class Factory
    {
        ///
        /// Generated by the generator
        ///
        public static Contracts.Base.IOpeningHoursAccess<QTHungryDogs.Logic.Entities.Base.OpeningHour> CreateOpeningHoursController() => new QTHungryDogs.Logic.Controllers.Base.OpeningHoursController();
        ///
        /// Generated by the generator
        ///
        public static Contracts.Base.IOpeningHoursAccess<QTHungryDogs.Logic.Entities.Base.OpeningHour> CreateOpeningHoursController(Object otherController)
        {
            var controllerObject = otherController as Controllers.ControllerObject;
            return new QTHungryDogs.Logic.Controllers.Base.OpeningHoursController(controllerObject ?? throw new Modules.Exceptions.LogicException(Modules.Exceptions.ErrorType.InvalidControllerObject));
        }
        ///
        /// Generated by the generator
        ///
        public static Contracts.Base.IRestaurantsAccess<QTHungryDogs.Logic.Entities.Base.Restaurant> CreateRestaurantsController() => new QTHungryDogs.Logic.Controllers.Base.RestaurantsController();
        ///
        /// Generated by the generator
        ///
        public static Contracts.Base.IRestaurantsAccess<QTHungryDogs.Logic.Entities.Base.Restaurant> CreateRestaurantsController(Object otherController)
        {
            var controllerObject = otherController as Controllers.ControllerObject;
            return new QTHungryDogs.Logic.Controllers.Base.RestaurantsController(controllerObject ?? throw new Modules.Exceptions.LogicException(Modules.Exceptions.ErrorType.InvalidControllerObject));
        }
        ///
        /// Generated by the generator
        ///
        public static Contracts.App.ISpecialOpeningHoursAccess<QTHungryDogs.Logic.Entities.App.SpecialOpeningHour> CreateSpecialOpeningHoursController() => new QTHungryDogs.Logic.Controllers.App.SpecialOpeningHoursController();
        ///
        /// Generated by the generator
        ///
        public static Contracts.App.ISpecialOpeningHoursAccess<QTHungryDogs.Logic.Entities.App.SpecialOpeningHour> CreateSpecialOpeningHoursController(Object otherController)
        {
            var controllerObject = otherController as Controllers.ControllerObject;
            return new QTHungryDogs.Logic.Controllers.App.SpecialOpeningHoursController(controllerObject ?? throw new Modules.Exceptions.LogicException(Modules.Exceptions.ErrorType.InvalidControllerObject));
        }
    }
}
