//@GeneratedCode
namespace QTHungryDogs.Logic.Controllers.App
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class SpecialOpeningHoursController : Controllers.GenericController<Entities.App.SpecialOpeningHour>, Contracts.App.ISpecialOpeningHoursAccess<Entities.App.SpecialOpeningHour>
    {
        ///
        /// Generated by the generator
        ///
        static SpecialOpeningHoursController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public SpecialOpeningHoursController()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public SpecialOpeningHoursController(ControllerObject other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
    }
}
