//@GeneratedCode
namespace QTHungryDogs.Logic.Contracts.Base
{
    ///
    /// Generated by the generator
    ///
    public partial interface IRestaurantXUsersAccess<T> : Contracts.IDataAccess<T>
    {
    }
}
