//@GeneratedCode
namespace QTHungryDogs.WebApi.Controllers.App
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class SpecialOpeningHoursController : Controllers.GenericController<QTHungryDogs.Logic.Entities.App.SpecialOpeningHour, QTHungryDogs.WebApi.Models.App.SpecialOpeningHourEdit, QTHungryDogs.WebApi.Models.App.SpecialOpeningHour>
    {
        ///
        /// Generated by the generator
        ///
        static SpecialOpeningHoursController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public SpecialOpeningHoursController(QTHungryDogs.Logic.Contracts.App.ISpecialOpeningHoursAccess<QTHungryDogs.Logic.Entities.App.SpecialOpeningHour> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTHungryDogs.WebApi.Models.App.SpecialOpeningHour ToOutModel(QTHungryDogs.Logic.Entities.App.SpecialOpeningHour accessModel)
        {
            var handled = false;
            var result = default(QTHungryDogs.WebApi.Models.App.SpecialOpeningHour);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTHungryDogs.WebApi.Models.App.SpecialOpeningHour.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTHungryDogs.Logic.Entities.App.SpecialOpeningHour accessModel, ref QTHungryDogs.WebApi.Models.App.SpecialOpeningHour? outModel, ref bool handled);
        partial void AfterToOutModel(QTHungryDogs.WebApi.Models.App.SpecialOpeningHour outModel);
    }
}
