//@GeneratedCode
namespace QTHungryDogs.AspMvc.Controllers.App
{
    using Microsoft.AspNetCore.Mvc;
    using TAccessModel = QTHungryDogs.Logic.Entities.App.SpecialOpeningHour;
    using TViewModel = QTHungryDogs.AspMvc.Models.App.SpecialOpeningHour;
    using TFilterModel = QTHungryDogs.AspMvc.Models.App.SpecialOpeningHourFilter;
    using TAccessContract = QTHungryDogs.Logic.Contracts.App.ISpecialOpeningHoursAccess<QTHungryDogs.Logic.Entities.App.SpecialOpeningHour>;
    ///
    /// Generated by the generator
    ///
    public sealed partial class SpecialOpeningHoursController : Controllers.FilterGenericController<TAccessModel, TViewModel, TFilterModel, TAccessContract>
    {
        ///
        /// Generated by the generator
        ///
        static SpecialOpeningHoursController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        protected override string ControllerName => "SpecialOpeningHours";
        ///
        /// Generated by the generator
        ///
        public SpecialOpeningHoursController(QTHungryDogs.Logic.Contracts.App.ISpecialOpeningHoursAccess<TAccessModel> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override TViewModel ToViewModel(TAccessModel accessModel, ActionMode actionMode)
        {
            var handled = false;
            var result = default(TViewModel);
            BeforeToViewModel(accessModel, actionMode, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = TViewModel.Create(accessModel);
            }
            AfterToViewModel(result, actionMode);
            return BeforeView(result, actionMode);
        }
        partial void BeforeToViewModel(TAccessModel accessModel, ActionMode actionMode, ref TViewModel? viewModel, ref bool handled);
        partial void AfterToViewModel(TViewModel viewModel, ActionMode actionMode);
    }
}
