//@GeneratedCode
namespace QTHungryDogs.Logic.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class OpeningHoursController : Controllers.GenericController<Entities.Base.OpeningHour>, Contracts.Base.IOpeningHoursAccess<Entities.Base.OpeningHour>
    {
        ///
        /// Generated by the generator
        ///
        static OpeningHoursController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public OpeningHoursController()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public OpeningHoursController(ControllerObject other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
    }
}
