//@GeneratedCode
namespace QTHungryDogs.Logic.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class RestaurantXUsersController : Controllers.GenericController<Entities.Base.RestaurantXUser>, Contracts.Base.IRestaurantXUsersAccess<Entities.Base.RestaurantXUser>
    {
        ///
        /// Generated by the generator
        ///
        static RestaurantXUsersController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public RestaurantXUsersController()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public RestaurantXUsersController(ControllerObject other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
    }
}
