//@GeneratedCode
namespace QTHungryDogs.Logic.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class RestaurantXIdentitiesController : Controllers.GenericController<Entities.Base.RestaurantXIdentity>, Contracts.Base.IRestaurantXIdentitiesAccess<Entities.Base.RestaurantXIdentity>
    {
        ///
        /// Generated by the generator
        ///
        static RestaurantXIdentitiesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public RestaurantXIdentitiesController()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public RestaurantXIdentitiesController(ControllerObject other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
    }
}
