//@GeneratedCode
namespace QTHungryDogs.WebApi.Models.Base
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class RestaurantXUser
    {
        ///
        /// Generated by the generator
        ///
        static RestaurantXUser()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public RestaurantXUser()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.Int32 RestaurantId
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Int32 UserId
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public QTHungryDogs.WebApi.Models.Base.Restaurant? Restaurant
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public static QTHungryDogs.WebApi.Models.Base.RestaurantXUser Create()
        {
            BeforeCreate();
            var result = new QTHungryDogs.WebApi.Models.Base.RestaurantXUser();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTHungryDogs.WebApi.Models.Base.RestaurantXUser Create(object other)
        {
            BeforeCreate(other);
            CommonBase.Extensions.ObjectExtensions.CheckArgument(other, nameof(other));
            var result = new QTHungryDogs.WebApi.Models.Base.RestaurantXUser();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTHungryDogs.WebApi.Models.Base.RestaurantXUser instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTHungryDogs.WebApi.Models.Base.RestaurantXUser instance, object other);
        ///
        /// Generated by the generator
        ///
        public static QTHungryDogs.WebApi.Models.Base.RestaurantXUser Create(QTHungryDogs.Logic.Entities.Base.RestaurantXUser other)
        {
            BeforeCreate(other);
            var result = new QTHungryDogs.WebApi.Models.Base.RestaurantXUser();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate(QTHungryDogs.Logic.Entities.Base.RestaurantXUser other);
        static partial void AfterCreate(QTHungryDogs.WebApi.Models.Base.RestaurantXUser instance, QTHungryDogs.Logic.Entities.Base.RestaurantXUser other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTHungryDogs.Logic.Entities.Base.RestaurantXUser other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                RestaurantId = other.RestaurantId;
                UserId = other.UserId;
                Restaurant = other.Restaurant != null ? QTHungryDogs.WebApi.Models.Base.Restaurant.Create((object)other.Restaurant) : null;
                RowVersion = other.RowVersion;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTHungryDogs.Logic.Entities.Base.RestaurantXUser other, ref bool handled);
        partial void AfterCopyProperties(QTHungryDogs.Logic.Entities.Base.RestaurantXUser other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTHungryDogs.WebApi.Models.Base.RestaurantXUser other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                RestaurantId = other.RestaurantId;
                UserId = other.UserId;
                Restaurant = other.Restaurant;
                RowVersion = other.RowVersion;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTHungryDogs.WebApi.Models.Base.RestaurantXUser other, ref bool handled);
        partial void AfterCopyProperties(QTHungryDogs.WebApi.Models.Base.RestaurantXUser other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Base.RestaurantXUser other)
            {
                result = IsEqualsWith(RowVersion, other.RowVersion)
                && Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return HashCode.Combine(RestaurantId, UserId, Restaurant, RowVersion, Id);
        }
    }
}
