//@GeneratedCode
namespace QTHungryDogs.Logic.Contracts.App
{
    ///
    /// Generated by the generator
    ///
    public partial interface ISpecialOpeningHoursAccess<T> : Contracts.IDataAccess<T>
    {
    }
}
