//@GeneratedCode
namespace QTHungryDogs.AspMvc.Models.Base
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class RestaurantXIdentity
    {
        ///
        /// Generated by the generator
        ///
        static RestaurantXIdentity()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public RestaurantXIdentity()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.Int32 RestaurantId
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Int32 IdentityId
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public QTHungryDogs.AspMvc.Models.Base.Restaurant? Restaurant
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public static QTHungryDogs.AspMvc.Models.Base.RestaurantXIdentity Create()
        {
            BeforeCreate();
            var result = new QTHungryDogs.AspMvc.Models.Base.RestaurantXIdentity();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTHungryDogs.AspMvc.Models.Base.RestaurantXIdentity Create(object other)
        {
            BeforeCreate(other);
            CommonBase.Extensions.ObjectExtensions.CheckArgument(other, nameof(other));
            var result = new QTHungryDogs.AspMvc.Models.Base.RestaurantXIdentity();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTHungryDogs.AspMvc.Models.Base.RestaurantXIdentity instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTHungryDogs.AspMvc.Models.Base.RestaurantXIdentity instance, object other);
        ///
        /// Generated by the generator
        ///
        public static QTHungryDogs.AspMvc.Models.Base.RestaurantXIdentity Create(QTHungryDogs.Logic.Entities.Base.RestaurantXIdentity other)
        {
            BeforeCreate(other);
            var result = new QTHungryDogs.AspMvc.Models.Base.RestaurantXIdentity();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate(QTHungryDogs.Logic.Entities.Base.RestaurantXIdentity other);
        static partial void AfterCreate(QTHungryDogs.AspMvc.Models.Base.RestaurantXIdentity instance, QTHungryDogs.Logic.Entities.Base.RestaurantXIdentity other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTHungryDogs.Logic.Entities.Base.RestaurantXIdentity other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                RestaurantId = other.RestaurantId;
                IdentityId = other.IdentityId;
                Restaurant = other.Restaurant != null ? QTHungryDogs.AspMvc.Models.Base.Restaurant.Create((object)other.Restaurant) : null;
                RowVersion = other.RowVersion;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTHungryDogs.Logic.Entities.Base.RestaurantXIdentity other, ref bool handled);
        partial void AfterCopyProperties(QTHungryDogs.Logic.Entities.Base.RestaurantXIdentity other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTHungryDogs.AspMvc.Models.Base.RestaurantXIdentity other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                RestaurantId = other.RestaurantId;
                IdentityId = other.IdentityId;
                Restaurant = other.Restaurant;
                RowVersion = other.RowVersion;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTHungryDogs.AspMvc.Models.Base.RestaurantXIdentity other, ref bool handled);
        partial void AfterCopyProperties(QTHungryDogs.AspMvc.Models.Base.RestaurantXIdentity other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Base.RestaurantXIdentity other)
            {
                result = IsEqualsWith(RowVersion, other.RowVersion)
                && Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return HashCode.Combine(RestaurantId, IdentityId, Restaurant, RowVersion, Id);
        }
    }
}
