//@GeneratedCode
namespace QTHungryDogs.WebApi.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class OpeningHoursController : Controllers.GenericController<QTHungryDogs.Logic.Entities.Base.OpeningHour, QTHungryDogs.WebApi.Models.Base.OpeningHourEdit, QTHungryDogs.WebApi.Models.Base.OpeningHour>
    {
        ///
        /// Generated by the generator
        ///
        static OpeningHoursController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public OpeningHoursController(QTHungryDogs.Logic.Contracts.Base.IOpeningHoursAccess<QTHungryDogs.Logic.Entities.Base.OpeningHour> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTHungryDogs.WebApi.Models.Base.OpeningHour ToOutModel(QTHungryDogs.Logic.Entities.Base.OpeningHour accessModel)
        {
            var handled = false;
            var result = default(QTHungryDogs.WebApi.Models.Base.OpeningHour);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTHungryDogs.WebApi.Models.Base.OpeningHour.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTHungryDogs.Logic.Entities.Base.OpeningHour accessModel, ref QTHungryDogs.WebApi.Models.Base.OpeningHour? outModel, ref bool handled);
        partial void AfterToOutModel(QTHungryDogs.WebApi.Models.Base.OpeningHour outModel);
    }
}
