//@GeneratedCode
namespace QTHungryDogs.WebApi.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class RestaurantsController : Controllers.GenericController<QTHungryDogs.Logic.Entities.Base.Restaurant, QTHungryDogs.WebApi.Models.Base.RestaurantEdit, QTHungryDogs.WebApi.Models.Base.Restaurant>
    {
        ///
        /// Generated by the generator
        ///
        static RestaurantsController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public RestaurantsController(QTHungryDogs.Logic.Contracts.Base.IRestaurantsAccess<QTHungryDogs.Logic.Entities.Base.Restaurant> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTHungryDogs.WebApi.Models.Base.Restaurant ToOutModel(QTHungryDogs.Logic.Entities.Base.Restaurant accessModel)
        {
            var handled = false;
            var result = default(QTHungryDogs.WebApi.Models.Base.Restaurant);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTHungryDogs.WebApi.Models.Base.Restaurant.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTHungryDogs.Logic.Entities.Base.Restaurant accessModel, ref QTHungryDogs.WebApi.Models.Base.Restaurant? outModel, ref bool handled);
        partial void AfterToOutModel(QTHungryDogs.WebApi.Models.Base.Restaurant outModel);
    }
}
