//@GeneratedCode
namespace QTHungryDogs.WebApi.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class RestaurantXUsersController : Controllers.GenericController<QTHungryDogs.Logic.Entities.Base.RestaurantXUser, QTHungryDogs.WebApi.Models.Base.RestaurantXUserEdit, QTHungryDogs.WebApi.Models.Base.RestaurantXUser>
    {
        ///
        /// Generated by the generator
        ///
        static RestaurantXUsersController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public RestaurantXUsersController(QTHungryDogs.Logic.Contracts.Base.IRestaurantXUsersAccess<QTHungryDogs.Logic.Entities.Base.RestaurantXUser> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTHungryDogs.WebApi.Models.Base.RestaurantXUser ToOutModel(QTHungryDogs.Logic.Entities.Base.RestaurantXUser accessModel)
        {
            var handled = false;
            var result = default(QTHungryDogs.WebApi.Models.Base.RestaurantXUser);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTHungryDogs.WebApi.Models.Base.RestaurantXUser.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTHungryDogs.Logic.Entities.Base.RestaurantXUser accessModel, ref QTHungryDogs.WebApi.Models.Base.RestaurantXUser? outModel, ref bool handled);
        partial void AfterToOutModel(QTHungryDogs.WebApi.Models.Base.RestaurantXUser outModel);
    }
}
