//@GeneratedCode
namespace QTHungryDogs.WebApi.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class RestaurantXIdentitiesController : Controllers.GenericController<QTHungryDogs.Logic.Entities.Base.RestaurantXIdentity, QTHungryDogs.WebApi.Models.Base.RestaurantXIdentityEdit, QTHungryDogs.WebApi.Models.Base.RestaurantXIdentity>
    {
        ///
        /// Generated by the generator
        ///
        static RestaurantXIdentitiesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public RestaurantXIdentitiesController(QTHungryDogs.Logic.Contracts.Base.IRestaurantXIdentitiesAccess<QTHungryDogs.Logic.Entities.Base.RestaurantXIdentity> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTHungryDogs.WebApi.Models.Base.RestaurantXIdentity ToOutModel(QTHungryDogs.Logic.Entities.Base.RestaurantXIdentity accessModel)
        {
            var handled = false;
            var result = default(QTHungryDogs.WebApi.Models.Base.RestaurantXIdentity);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTHungryDogs.WebApi.Models.Base.RestaurantXIdentity.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTHungryDogs.Logic.Entities.Base.RestaurantXIdentity accessModel, ref QTHungryDogs.WebApi.Models.Base.RestaurantXIdentity? outModel, ref bool handled);
        partial void AfterToOutModel(QTHungryDogs.WebApi.Models.Base.RestaurantXIdentity outModel);
    }
}
