using Microsoft.AspNetCore.Mvc;

namespace QTHungryDogs.WebApi.Controllers.Base
{
    ///
    /// Generated by the developer
    ///
    [Route("api/[controller]")]
    [ApiController]
    public class StoreManagerRestaurantsController : ApiControllerBase
    {
        /// <summary>
        /// Query all store manager restaurants.
        /// </summary>
        /// <returns>The query result.</returns>
        [HttpGet("QueryRestaurants", Name = nameof(QueryRestaurantsAsync))]
        public async Task<Models.Base.Restaurant[]> QueryRestaurantsAsync()
        {
            var instanceAccess = HttpContext.RequestServices.GetRequiredService<Logic.Contracts.Base.IRestaurantsAccess<Logic.Entities.Base.Restaurant>>();
            var entities = Array.Empty<Logic.Entities.Base.Restaurant>();

            if (instanceAccess != null)
            {
                instanceAccess.SessionToken = GetSessionToken();
                entities = await instanceAccess.QueryStoreManagerRestaurantsAsync();
            }
            return entities.Select(e => Models.Base.Restaurant.Create(e)).ToArray();
        }
    }
}
