//@CodeCopy
//MdStart
#if ACCOUNT_ON
namespace QTHungryDogs.WebApi.Controllers.Account
{
    using TAccessModel = QTHungryDogs.Logic.Models.Account.Identity;
    using TOutModel = QTHungryDogs.WebApi.Models.Account.Identity;
    using TEditModel = QTHungryDogs.WebApi.Models.Account.IdentityEdit;
    ///
    /// Generated by the generator
    ///
    public sealed partial class IdentitiesController : Controllers.GenericController<TAccessModel, TEditModel, TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static IdentitiesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public IdentitiesController(QTHungryDogs.Logic.Contracts.Account.IIdentitiesAccess<TAccessModel> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override TOutModel ToOutModel(TAccessModel accessModel)
        {
            var handled = false;
            var result = default(TOutModel);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = TOutModel.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(TAccessModel accessModel, ref TOutModel? outModel, ref bool handled);
        partial void AfterToOutModel(TOutModel outModel);
    }
}
#endif
//MdEnd
