//@GeneratedCode
namespace QTHungryDogs.Logic.DataContext
{
    ///
    /// Generated by the generator
    ///
    partial class ProjectDbContext
    {
        ///
        /// Generated by the generator
        ///
        public DbSet<QTHungryDogs.Logic.Entities.Base.OpeningHour>? OpeningHourSet
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public DbSet<QTHungryDogs.Logic.Entities.Base.Restaurant>? RestaurantSet
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public DbSet<QTHungryDogs.Logic.Entities.App.SpecialOpeningHour>? SpecialOpeningHourSet
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        partial void GetGeneratorDbSet<E>(ref DbSet<E>? dbSet, ref bool handled) where E : Entities.IdentityEntity
        {
            if (typeof(E) == typeof(QTHungryDogs.Logic.Entities.Base.OpeningHour))
            {
                dbSet = OpeningHourSet as DbSet<E>;
                handled = true;
            }
            if (typeof(E) == typeof(QTHungryDogs.Logic.Entities.Base.Restaurant))
            {
                dbSet = RestaurantSet as DbSet<E>;
                handled = true;
            }
            if (typeof(E) == typeof(QTHungryDogs.Logic.Entities.App.SpecialOpeningHour))
            {
                dbSet = SpecialOpeningHourSet as DbSet<E>;
                handled = true;
            }
        }
    }
}
